COCOMO
float COCOMO::a
The value of the multiplier.
Referenced by getEstimate, setConstants.
float COCOMO::b
The value of the exponent.
Referenced by getEstimate, setConstants.
float COCOMO::kdsi
The lines of code in thousands.
Referenced by getEstimate, setKDSI.
float COCOMO::costDriverValues[costDriverSize][6][costDriverSize][6]
Cost drivers used for refining the estimate in intermediate COCOMO. Rankings: very low, low, nominal, high, very high, extra high
Referenced by getEstimate.
float COCOMO::costDrivers[costDriverSize][costDriverSize]
Used for selecting the cost driver values.
Referenced by getEstimate, setCostDrivers, initCostDrivers.
COCOMO::COCOMO()=default
Default constructor.
float COCOMO::getEstimate()
Performs COCOMO calculations.
References a, kdsi, b, costDriverSize, costDriverValues, costDrivers.
Referenced by COCOMOHelper.
void COCOMO::setConstants(short mode, bool isIntermediate)
A mutator for a and b.
mode is a short. 1 = organic, 2 = semi-detached, 3 = embedded, default is organic. isIntermediate is a bool. It determines whether to set a and b according to basic or intermediate COCOMO values.
References a, b.
Referenced by COCOMOHelper.
void COCOMO::setKDSI(float kdsi)
A mutator for the estimated thousand lines of code.
References kdsi.
Referenced by COCOMOHelper.
void COCOMO::setCostDrivers(float values[costDriverSize])
A mutator for costDrivers[].
References costDriverSize, costDrivers.
Referenced by COCOMOHelper.
void COCOMO::initCostDrivers()
Initializes all costDriver values to the semi-detached values.
References costDriverSize, costDrivers.
Referenced by COCOMOHelper.