FunctionPoint
const short FunctionPoint::input[3][3]
holds complexity values for the input type of component
Referenced by getEstimate.
const short FunctionPoint::output[3][3]
holds complexity values for the output type of component
Referenced by getEstimate.
const short FunctionPoint::inquiry[3][3]
holds complexity values for the inquiry type of component
Referenced by getEstimate.
const short FunctionPoint::master[3][3]
holds complexity values for the master type of component
Referenced by getEstimate.
const short FunctionPoint::interface[3][3]
holds complexity values for the interface type of component
Referenced by getEstimate.
short FunctionPoint::inp
holds index for selecting input complexity
Referenced by setComplexities, getEstimate.
short FunctionPoint::out
holds index for selecting output complexity
Referenced by setComplexities, getEstimate.
short FunctionPoint::inq
holds index for selecting inquiry complexity
Referenced by setComplexities, getEstimate.
short FunctionPoint::maf
holds index for selecting master complexity
Referenced by setComplexities, getEstimate.
short FunctionPoint::inf
holds index for selecting interface complexity
Referenced by setComplexities, getEstimate.
int FunctionPoint::nInp
Number of inputs.
Referenced by setComponents, getEstimate.
int FunctionPoint::nOut
Number of outputs.
Referenced by setComponents, getEstimate.
int FunctionPoint::nInq
Number of inquiries.
Referenced by setComponents, getEstimate.
int FunctionPoint::nMaf
Number of masters.
Referenced by setComponents, getEstimate.
int FunctionPoint::nInf
Number of interfaces.
Referenced by setComponents, getEstimate.
short FunctionPoint::dcomm
Measure of influence for data communication.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::dpro
Measure of influence for distributed data processing.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::perf
Measure of influence for performance criteria.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::util
Measure of influence for heavily utilized hardware.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::trans
Measure of influence for high transaction rates.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::entry
Measure of influence for online data entry.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::eff
Measure of influence for end-user proficiency.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::upd
Measure of influence for online updating.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::comp
Measure of influence for complex computations.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::reuse
Measure of influence for reusability.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::inst
Measure of influence for ease of installation.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::oper
Measure of influence for ease of operation.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::port
Measure of influence for portability.
Referenced by setTechnicalFactors, getEstimate.
short FunctionPoint::maint
Measure of influence for maintainability.
Referenced by setTechnicalFactors, getEstimate.
FunctionPoint::FunctionPoint()=default
Default Constructor.
float FunctionPoint::getEstimate()
Performs function points calculation.
References nInp, input, inp, nOut, output, out, nInq, inquiry, inq, nMaf, master, maf, nInf, interface, inf, dcomm, dpro, perf, util, trans, entry, eff, upd, comp, reuse, inst, oper, port, maint.
Referenced by FunctionPointHelper.
void FunctionPoint::setComplexities(short inp, short out, short inq, short maf, short inf)
A mutator for complexities.
References inp, out, inq, maf, inf.
Referenced by FunctionPointHelper.
void FunctionPoint::setComponents(int nInp, int nOut, int nInq, int nMaf, int nInf)
A mutator for components for Unadjusted Function Points (UFP)
References nInp, nOut, nInq, nMaf, nInf.
Referenced by FunctionPointHelper.
void FunctionPoint::setTechnicalFactors(int dcomm, int dpro, int perf, int util, int trans, int entry, int eff, int upd, int comp, int reuse, int inst, int oper, int port, int maint)
A mutator for factors for Degree of Influence (DI) and Technical Complexity Factors (TCF)
References dcomm, dpro, perf, util, trans, entry, eff, upd, comp, reuse, inst, oper, port, maint.
Referenced by FunctionPointHelper.